# Generated by Django 4.1.7 on 2023-04-13 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CustomAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TbSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255)),
                ('section_description', models.CharField(blank=True, max_length=255, null=True)),
                ('section_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='image_sections/')),
                ('child_age', models.CharField(blank=True, max_length=30, null=True)),
                ('admin_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childrenhealthcare.customadmin')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255, verbose_name='Video Name')),
                ('video_path', models.FileField(max_length=255, upload_to='Videos/', verbose_name='Video')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childrenhealthcare.category')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_age', models.CharField(blank=True, choices=[('Pregnancy', 'Pregnancy'), ('0-3 months', '0-3 months'), ('3-12 months', '3-12 months'), ('1-3 years', '1-3 years'), ('Autism', 'Autism'), ('Disability', 'Disability')], max_length=40, null=True, verbose_name='user section')),
                ('email_verified', models.BooleanField(default=False)),
                ('code_verification', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='TbSubsections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_name', models.CharField(max_length=255, verbose_name='SubSection Name')),
                ('subsection_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='SubSection_Image/', verbose_name='SubSection Image')),
                ('subsection_icon', models.ImageField(blank=True, max_length=255, null=True, upload_to='SubSection_Image/', verbose_name='SubSection Icon')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childrenhealthcare.tbsections')),
            ],
            options={
                'verbose_name': 'Subsection',
                'verbose_name_plural': 'Subsections',
            },
        ),
        migrations.CreateModel(
            name='Subtitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.FileField(blank=True, max_length=255, null=True, upload_to='Subtitle/', verbose_name='Subtitle')),
                ('video_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childrenhealthcare.videos')),
            ],
            options={
                'verbose_name': 'Subtitle',
                'verbose_name_plural': 'Subtitles',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childrenhealthcare.tbsubsections'),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('article_details', models.TextField(verbose_name='Subject')),
                ('image_path', models.ImageField(blank=True, max_length=255, null=True, upload_to='Articles_Images', verbose_name='Image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childrenhealthcare.category')),
            ],
            options={
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Comment')),
                ('article_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childrenhealthcare.articles', verbose_name='Article')),
                ('user_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childrenhealthcare.userdata', verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'unique_together': {('user_ID', 'article_ID')},
            },
        ),
    ]
