# Generated by Django 4.1.7 on 2023-05-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenhealthcare', '0004_alter_videos_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitles',
            name='subtitle',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='Subtitles/', verbose_name='Subtitle'),
        ),
    ]
